"""
Author: Hatim
Extracts the PC-Addresses from the file generated by
`print-functions.py`. Assumes that the format is:
	PC-Address Label Function-Name
"""

import sys

if len(sys.argv) != 2:
	print ("Usage: python3 extract-address.py benchmark")
	sys.exit(1)

benchmark = sys.argv[1]
benchmark = benchmark.strip().lower()

# ISA = 'arm'
ISA = 'x86'

input_file = f"../../../../functions/pc-address/{ISA}/{benchmark}.pc.{ISA}"
output_file = f"../inputs/pc-address.txt"

with open(input_file, "r") as infile, open(output_file, "w") as outfile:
    for line in infile:
        words = line.strip()
        # print (words)
        address = words.split()[0]

        if ISA == "x86":
            print(address[-16:], file=outfile)
        else: # ISA == "arm"
            print(address[-8:], file=outfile)

